export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const ADD_PRODUCT_TO_CARD = "ADD_PRODUCT_TO_CARD";
export const REMOVE_PRODUCT_FROM_CARD = "REMOVE_PRODUCT_FROM_CARD";
export const CHANGE_VIEW = "CHANGE_VIEW";
export const DECREASE_PRODUCT_QTY = "DECREASE_PRODUCT_QTY";
export const INCREASE_PRODUCT_QTY = "INCREASE_PRODUCT_QTY";
